create table users (
                       id int generated by default as identity primary key,
                       username varchar(45) not null,
                       "password" varchar(45) not null,
                       "enabled"  int not null
);

create table authorities(
                            id int generated by default as identity primary key,
                            username varchar(45) not null,
                            authority varchar(45) not null
);

insert into authorities (username, authority)
values ('kubatea', 'write');

create table artist (
                        artist_id int generated by default as identity primary key,
                        "name" varchar(100) not null,
                        email varchar(100) not null,
                        mobile_number varchar(20) not null,
                        pwd varchar(500) not null,
                        "role" varchar(45) not null,
                        create_dt date default null
);

insert into artist(name, email, mobile_number, pwd, role, create_dt)
VALUES (
           'kubatea',
           'kuat@example.com',
           '87751234567',
           '$2y$12$oRRbkNfwuR8ug4MlzH5FOeui.//1mkd.RsOAJMbykTSupVy.x/vb2',
           'admin',
           current_date);

create table accounts (
                          artist_id int not null,
                          account_number int not null primary key,
                          account_type varchar(100) not null,
                          branch_address varchar(100) not null,
                          create_dt date default null,
                          constraint fk_artist foreign key(artist_id) references artist(artist_id) on delete cascade
);

insert into accounts(artist_id, account_number, account_type, branch_address, create_dt)
values (
           1,
           1865764534,
           'Savings',
           '123 Main Street, Almaty',
           current_date
       );

create table account_transactions (
                                      transaction_id varchar(200) not null primary key,
                                      account_number int not null,
                                      artist_id int not null,
                                      transaction_dt date not null,
                                      transaction_summary varchar(200) not null,
                                      transaction_type varchar(100) not null,
                                      transaction_amt int not null,
                                      closing_balance int not null,
                                      create_dt date default null,
                                      constraint accounts_ibfk_2 foreign key(account_number) references accounts(account_number) on delete cascade,
                                      constraint acct_user_ibfk_1 foreign key(artist_id) references artist(artist_id) on delete cascade
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO account_transactions (transaction_id, account_number, artist_id, transaction_dt, transaction_summary,
                                  transaction_type,transaction_amt,closing_balance, create_dt)
VALUES (
           uuid_generate_v4(),
           1865764534,
           1,
           current_date - interval '7 days',
           'Coffee Shop',
           'Withdrawal',
           30,
           34500,
           current_date - interval '7 days'
       );

INSERT INTO account_transactions (transaction_id, account_number, artist_id, transaction_dt, transaction_summary,
                                  transaction_type,transaction_amt,closing_balance, create_dt)
VALUES (uuid_generate_v4(),
        1865764534,
        1,
        current_date - interval '6 days',
        'Uber',
        'Withdrawal',
        100,
        34400,
        current_date - interval '6 days'
       );

INSERT INTO account_transactions (transaction_id, account_number, artist_id, transaction_dt, transaction_summary,
                                  transaction_type,transaction_amt,closing_balance, create_dt)
VALUES (uuid_generate_v4(),
        1865764534,
        1,
        current_date - interval '5 days',
        'Self Deposit',
        'Deposit',
        500,
        34900,
        current_date - interval '5 days');

INSERT INTO account_transactions (transaction_id, account_number, artist_id, transaction_dt, transaction_summary,
                                  transaction_type,transaction_amt,closing_balance, create_dt)
VALUES (uuid_generate_v4(),
        1865764534,
        1,
        current_date - interval '4 days',
        'Ebay',
        'Withdrawal',
        600,
        34300,
        current_date - interval '4 days');

INSERT INTO account_transactions (transaction_id, account_number, artist_id, transaction_dt, transaction_summary,
                                  transaction_type,transaction_amt,closing_balance, create_dt)
VALUES (uuid_generate_v4(),
        1865764534,
        1,
        current_date - interval '2 days',
        'OnlineTransfer',
        'Deposit',
        700,
        35000,
        current_date - interval '2 days');

INSERT INTO account_transactions (transaction_id, account_number, artist_id, transaction_dt, transaction_summary,
                                  transaction_type,transaction_amt,closing_balance, create_dt)
VALUES (
           uuid_generate_v4(),
           1865764534,
           1,
           current_date - interval '1 days',
           'Amazon.com', 'Withdrawal',
           100,
           34900,
           current_date - interval '1 days'
       );

create table loans (
                       loan_number serial primary key,
                       artist_id int not null,
                       start_dt date not null,
                       loan_type varchar(100) not null,
                       total_loan int not null,
                       amount_paid int not null,
                       outstanding_amount int not null,
                       create_dt date default null,
                       foreign key (artist_id) references artist(artist_id) on delete cascade
);

insert into loans (artist_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
values (1, '2020-10-13', 'Home', 200000, 50000, 150000, current_date);

insert into loans (artist_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
values (1, '2020-06-06', 'Vehicle', 40000, 10000, 30000, current_date);

insert into loans (artist_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
values (1, '2018-02-14', 'Home', 50000, 10000, 40000, current_date);

insert into loans (artist_id, start_dt, loan_type, total_loan, amount_paid, outstanding_amount, create_dt)
values (1, '2018-02-14', 'Personal', 10000, 3500, 6500, current_date);

create table cards (
                       card_id serial primary key,
                       card_number varchar(100) not null,
                       artist_id int not null,
                       card_type varchar(100) not null,
                       total_limit int not null,
                       amount_used int not null,
                       available_amount int not null,
                       create_dt date default null,
                       foreign key (artist_id) references artist(artist_id) on delete cascade
);

insert into cards (card_number, artist_id, card_type, total_limit, amount_used, available_amount, create_dt)
values ('4565XXXX4656', 1, 'Credit', 10000, 500, 9500, current_date);

insert into cards (card_number, artist_id, card_type, total_limit, amount_used, available_amount, create_dt)
values ('3455XXXX8673', 1, 'Credit', 7500, 600, 6900, current_date);

insert into cards (card_number, artist_id, card_type, total_limit, amount_used, available_amount, create_dt)
values ('2359XXXX9346', 1, 'Credit', 20000, 4000, 16000, current_date);

create table notice_details (
                                notice_id serial primary key,
                                notice_summary varchar(200) not null,
                                notice_details varchar(500) not null,
                                notic_beg_dt date not null,
                                notic_end_dt date default null,
                                create_dt date default null,
                                update_dt date default null
);

insert into notice_details (notice_summary, notice_details, notic_beg_dt, notic_end_dt, create_dt, update_dt)
values ('Home Loan Interest rates reduced', 'Home loan interest rates are reduced as per the government guidelines. The updated rates will be effective immediately',
        current_date - interval '30 days', current_date + interval '30 days', current_date, null);

insert into notice_details (notice_summary, notice_details, notic_beg_dt, notic_end_dt, create_dt, update_dt)
values ('Net Banking Offers', 'Customers who will opt for Internet banking while opening a saving account will get a $50 amazon voucher',
        current_date - interval '30 days', current_date + interval '30 days', current_date, null);

insert into notice_details (notice_summary, notice_details, notic_beg_dt, notic_end_dt, create_dt, update_dt)
values ('Mobile App Downtime', 'The mobile application of the EazyBank will be down from 2AM-5AM on 12/05/2020 due to maintenance activities',
        current_date - interval '30 days', current_date + interval '30 days', current_date, null);

insert into notice_details (notice_summary, notice_details, notic_beg_dt, notic_end_dt, create_dt, update_dt)
values ('E Auction notice', 'There will be an e-auction on 12/08/2020 on the Bank website for all the stubborn arrears. Interested parties can participate in the e-auction',
        current_date - interval '30 days', current_date + interval '30 days', current_date, null);

insert into notice_details (notice_summary, notice_details, notic_beg_dt, notic_end_dt, create_dt, update_dt)
values ('Launch of Millennia Cards', 'Millennia Credit Cards are launched for the premium customers of EazyBank. With these cards, you will get 5% cashback for each purchase',
        current_date - interval '30 days', current_date + interval '30 days', current_date, null);

insert into notice_details (notice_summary, notice_details, notic_beg_dt, notic_end_dt, create_dt, update_dt)
values ('COVID-19 Insurance', 'EazyBank launched an insurance policy which will cover COVID-19 expenses. Please reach out to the branch for more details',
        current_date - interval '30 days', current_date + interval '30 days', current_date, null);

create table contact_messages (
                                  contact_id varchar(50) primary key,
                                  contact_name varchar(50) not null,
                                  contact_email varchar(100) not null,
                                  subject varchar(500) not null,
                                  message varchar(2000) not null,
                                  create_dt date default null
);